[package]
name = "rust-crawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
futures = "0.3.21"
futures-timer = "3.0.2"
reqwest = "0.11.11"
thiserror = "1.0.31"
